"""
A script to render interpolant views from the source camera to the target camera using the DyCheck iPhone dataset.
NOTE: The provided depth map was not satisfactory enough to use directly, so we switched to using depth maps generated by VGGT.
NOTE: The images are center-cropped and reshaped to 518x518.
"""
from typing import Literal
import argparse
import concurrent.futures
import copy
import json
import os
import sys
import cv2
import lovely_tensors
import matplotlib.pyplot as plt
import numpy as np
import torch
from PIL import Image
from tqdm import tqdm

from einops import rearrange
from scipy.spatial.transform import Rotation, Slerp
from vggt.models.vggt import VGGT
from vggt.utils.load_fn import load_and_preprocess_images
from vggt.utils.pose_enc import pose_encoding_to_extri_intri

from trajectory_extraction import *

lovely_tensors.monkey_patch()


def load_json(filename: str, **kwargs) -> dict:
    with open(filename) as f:
        return json.load(f, **kwargs)


def load_img(filename: str, *, use_rgb: bool = True, **kwargs) -> np.ndarray:
    img = cv2.imread(filename, **kwargs)
    if use_rgb and img.shape[-1] >= 3:
        # Take care of RGBA case when flipping.
        img = np.concatenate([img[..., 2::-1], img[..., 3:]], axis=-1)
    return img


def matmul(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    assert isinstance(b, np.ndarray)
    return a @ b

def matv(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    return matmul(a, b[..., None])[..., 0]

def _compute_residual_and_jacobian(
    x: np.ndarray,
    y: np.ndarray,
    xd: np.ndarray,
    yd: np.ndarray,
    k1: float = 0.0,
    k2: float = 0.0,
    k3: float = 0.0,
    p1: float = 0.0,
    p2: float = 0.0,
) -> tuple[
    np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray
]:
    """Auxiliary function of radial_and_tangential_undistort()."""
    # let r(x, y) = x^2 + y^2;
    #     d(x, y) = 1 + k1 * r(x, y) + k2 * r(x, y) ^2 + k3 * r(x, y)^3;
    r = x * x + y * y
    d = 1.0 + r * (k1 + r * (k2 + k3 * r))

    # The perfect projection is:
    # xd = x * d(x, y) + 2 * p1 * x * y + p2 * (r(x, y) + 2 * x^2);
    # yd = y * d(x, y) + 2 * p2 * x * y + p1 * (r(x, y) + 2 * y^2);
    #
    # Let's define
    #
    # fx(x, y) = x * d(x, y) + 2 * p1 * x * y + p2 * (r(x, y) + 2 * x^2) - xd;
    # fy(x, y) = y * d(x, y) + 2 * p2 * x * y + p1 * (r(x, y) + 2 * y^2) - yd;
    #
    # We are looking for a solution that satisfies
    # fx(x, y) = fy(x, y) = 0;
    fx = d * x + 2 * p1 * x * y + p2 * (r + 2 * x * x) - xd
    fy = d * y + 2 * p2 * x * y + p1 * (r + 2 * y * y) - yd

    # Compute derivative of d over [x, y]
    d_r = k1 + r * (2.0 * k2 + 3.0 * k3 * r)
    d_x = 2.0 * x * d_r
    d_y = 2.0 * y * d_r

    # Compute derivative of fx over x and y.
    fx_x = d + d_x * x + 2.0 * p1 * y + 6.0 * p2 * x
    fx_y = d_y * x + 2.0 * p1 * x + 2.0 * p2 * y

    # Compute derivative of fy over x and y.
    fy_x = d_x * y + 2.0 * p2 * y + 2.0 * p1 * x
    fy_y = d + d_y * y + 2.0 * p2 * x + 6.0 * p1 * y

    return fx, fy, fx_x, fx_y, fy_x, fy_y


def _radial_and_tangential_undistort(
    xd: np.ndarray,
    yd: np.ndarray,
    k1: float = 0,
    k2: float = 0,
    k3: float = 0,
    p1: float = 0,
    p2: float = 0,
    eps: float = 1e-9,
    max_iterations: int = 10,
) -> tuple[np.ndarray, np.ndarray]:
    """Computes undistorted (x, y) from (xd, yd).

    Note that this function is purely running on CPU and thus could be slow.
    The original Nerfies & HyperNeRF are training on distorted raw images but
    with undistorted rays.
    """
    # Initialize from the distorted point.
    x = xd.copy()
    y = yd.copy()

    for _ in range(max_iterations):
        fx, fy, fx_x, fx_y, fy_x, fy_y = _compute_residual_and_jacobian(
            x=x, y=y, xd=xd, yd=yd, k1=k1, k2=k2, k3=k3, p1=p1, p2=p2
        )
        denominator = fy_x * fx_y - fx_x * fy_y
        x_numerator = fx * fy_y - fy * fx_y
        y_numerator = fy * fx_x - fx * fy_x
        step_x = np.where(
            np.abs(denominator) > eps,
            x_numerator / denominator,
            np.zeros_like(denominator),
        )
        step_y = np.where(
            np.abs(denominator) > eps,
            y_numerator / denominator,
            np.zeros_like(denominator),
        )

        x = x + step_x
        y = y + step_y

    return x, y


def points_to_local_points(
    points: np.ndarray,
    extrins: np.ndarray,
) -> np.ndarray:
    """Converts points from world to camera coordinates.

    Args:
        points (np.ndarray): A (..., 3) points tensor in world coordinates.
        extrins (np.ndarray): A (..., 4, 4) camera extrinsic tensor, specifying
            world-to-camera transform.

    Returns:
        np.ndarray: A (..., 3) points tensor in camera coordinates.
    """
    return matv(extrins[..., :3, :3], points) + extrins[..., :3, 3]


def project(
    points: np.ndarray,
    intrins: np.ndarray,
    extrins: np.ndarray,
    radial_distortions: Optional[np.ndarray] = None,
    tangential_distortions: Optional[np.ndarray] = None,
    *,
    return_depth: bool = False,
    use_projective_depth: bool = True,
) -> np.ndarray:
    """Projects 3D points to 2D pixels.

    This function supports batched operation and duck typing between numpy and
    jax.numpy arrays.

    Args:
        points (np.ndarray): A (..., 3) points tensor.
        intrins (np.ndarray): A (..., 3, 3) intrinsic matrix tensor.
        extrins (np.ndarray): A (..., 4, 4) extrinsic matrix tensor.
        radial_distortions (Optional[np.ndarray]): A (..., 3) radial
            distortion tensor.
        tangential_distortions (Optional[np.ndarray]): A (..., 2) tangential
            distortion tensor.
        return_depth: Whether to return depth.
        use_projective_depth: Whether to use projective depth.

    Returns:
        np.ndarray: A (..., 2) pixels tensor.
    """
    tensors_to_check = [intrins, extrins]
    if radial_distortions is not None:
        tensors_to_check.append(radial_distortions)
    if tangential_distortions is not None:
        tensors_to_check.append(tangential_distortions)
    if isinstance(points, np.ndarray):
        assert all([isinstance(x, np.ndarray) for x in tensors_to_check])
        np_or_jnp = np
    else:
        assert all([isinstance(x, jnp.ndarray) for x in tensors_to_check])
        np_or_jnp = jnp

    local_points = points_to_local_points(points, extrins)

    normalized_pixels = np_or_jnp.where(
        local_points[..., -1:] != 0,
        local_points[..., :2] / local_points[..., -1:],
        0,
    )
    r2 = (normalized_pixels**2).sum(axis=-1, keepdims=True)

    if radial_distortions is not None:
        # Apply radial distortion.
        radial_scalars = 1 + r2 * (
            radial_distortions[..., 0:1]
            + r2
            * (
                radial_distortions[..., 1:2]
                + r2 * radial_distortions[..., 2:3]
            )
        )
    else:
        radial_scalars = 1

    if tangential_distortions is not None:
        # Apply tangential distortion.
        tangential_deltas = 2 * tangential_distortions * np_or_jnp.prod(
            normalized_pixels,
            axis=-1,
            keepdims=True,
        ) + tangential_distortions[..., ::-1] * (
            r2 + 2 * normalized_pixels**2
        )
    else:
        tangential_deltas = 0

    # Apply distortion.
    normalized_pixels = normalized_pixels * radial_scalars + tangential_deltas

    # Map the distorted ray to the image plane and return the depth.
    pixels = matv(
        intrins,
        np_or_jnp.concatenate(
            [
                normalized_pixels,
                np_or_jnp.ones_like(normalized_pixels[..., :1]),
            ],
            axis=-1,
        ),
    )[..., :2]

    if not return_depth:
        return pixels
    else:
        depths = (
            local_points[..., 2:]
            if use_projective_depth
            else np_or_jnp.linalg.norm(local_points, axis=-1, keepdims=True)
        )
        return pixels, depths


class Camera:
    """A generic camera class that potentially distorts rays.

    This camera class uses OpenCV camera model, whhere the local-to-world
    transform assumes (right, down, forward).

    Attributes:
        orientation (np.ndarray): The orientation of the camera of shape (3, 3)
            that maps the world coordinates to local coordinates.
        position (np.ndarray): The position of the camera of shape (3,) in the
            world coordinates.
        focal_length (np.ndarray | float): The focal length of the camera.
        principal_point (np.ndarray): The principal point of the camera of
            shape (2,)
        image_size (np.ndarray): The image size (W, H).
        skew (np.ndarray | float): The skewness of the camera.
        pixel_aspect_ratio (np.ndarray | float): The pixel aspect ratio.
        radial_distortion (Optional[np.ndarray]): The radial distortion of the
            camera of shape (3,).
        tangential_distortion (Optional[np.ndarray]): The tangential distortion
            of the camera of shape (2,).
    """

    def __init__(
        self,
        orientation: np.ndarray,
        position: np.ndarray,
        focal_length: np.ndarray | float,
        principal_point: np.ndarray,
        image_size: np.ndarray,
        skew: np.ndarray | float = 0.0,
        pixel_aspect_ratio: np.ndarray | float = 1.0,
        radial_distortion: Optional[np.ndarray] = None,
        tangential_distortion: Optional[np.ndarray] = None,
        *,
        use_center: bool = True,
        use_projective_depth: bool = True,
    ):
        """Constructor for camera class."""
        if radial_distortion is None:
            radial_distortion = np.array([0, 0, 0], np.float32)
        if tangential_distortion is None:
            tangential_distortion = np.array([0, 0], np.float32)

        self.orientation = np.array(orientation, np.float32)
        self.position = np.array(position, np.float32)
        self.focal_length = np.array(focal_length, np.float32)
        self.principal_point = np.array(principal_point, np.float32)
        self.image_size = np.array(image_size, np.uint32)

        # Distortion parameters.
        self.skew = np.array(skew, np.float32)
        self.pixel_aspect_ratio = np.array(pixel_aspect_ratio, np.float32)
        self.radial_distortion = np.array(radial_distortion, np.float32)
        self.tangential_distortion = np.array(
            tangential_distortion, np.float32
        )

        self.use_center = use_center
        self.use_projective_depth = use_projective_depth

    @classmethod
    def fromjson(cls, filename: str):
        camera_dict = load_json(filename)

        # Fix old camera JSON.
        if "tangential" in camera_dict:
            camera_dict["tangential_distortion"] = camera_dict["tangential"]

        return cls(
            orientation=np.asarray(camera_dict["orientation"]),
            position=np.asarray(camera_dict["position"]),
            focal_length=camera_dict["focal_length"],
            principal_point=np.asarray(camera_dict["principal_point"]),
            image_size=np.asarray(camera_dict["image_size"]),
            skew=camera_dict["skew"],
            pixel_aspect_ratio=camera_dict["pixel_aspect_ratio"],
            radial_distortion=np.asarray(camera_dict["radial_distortion"]),
            tangential_distortion=np.asarray(
                camera_dict["tangential_distortion"]
            ),
        )

    def asdict(self):
        return {
            "orientation": self.orientation,
            "position": self.position,
            "focal_length": self.focal_length,
            "principal_point": self.principal_point,
            "image_size": self.image_size,
            "skew": self.skew,
            "pixel_aspect_ratio": self.pixel_aspect_ratio,
            "radial_distortion": self.radial_distortion,
            "tangential_distortion": self.tangential_distortion,
        }

    @property
    def scale_factor_x(self):
        return self.focal_length

    @property
    def scale_factor_y(self):
        return self.focal_length * self.pixel_aspect_ratio

    @property
    def principal_point_x(self):
        return self.principal_point[0]

    @property
    def principal_point_y(self):
        return self.principal_point[1]

    @property
    def has_tangential_distortion(self):
        return any(self.tangential_distortion != 0)

    @property
    def has_radial_distortion(self):
        return any(self.radial_distortion != 0)

    @property
    def distortion(self):
        """Camera distortion parameters compatible with OpenCV.

        Reference:
            https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html
        """
        return np.concatenate(
            [
                self.radial_distortion[:2],
                self.tangential_distortion,
                self.radial_distortion[-1:],
            ]
        )

    @property
    def image_size_y(self):
        return self.image_size[1]

    @property
    def image_size_x(self):
        return self.image_size[0]

    @property
    def image_shape(self):
        return np.array([self.image_size_y, self.image_size_x], np.uint32)

    @property
    def optical_axis(self):
        return self.orientation[2, :]

    @property
    def up_axis(self):
        return -self.orientation[1, :]

    @property
    def translation(self):
        return -self.orientation @ self.position

    @property
    def intrin(self):
        return np.array(
            [
                [self.scale_factor_x, self.skew, self.principal_point_x],
                [0, self.scale_factor_y, self.principal_point_y],
                [0, 0, 1],
            ],
            np.float32,
        )

    @property
    def extrin(self):
        # 4x4 world-to-camera transform.
        return np.concatenate(
            [
                np.concatenate(
                    [self.orientation, self.translation[..., None]], axis=-1
                ),
                np.array([[0, 0, 0, 1]], np.float32),
            ],
            axis=-2,
        )

    def undistort_pixels(self, pixels: np.ndarray) -> np.ndarray:
        y = (pixels[..., 1] - self.principal_point_y) / self.scale_factor_y
        x = (
            pixels[..., 0] - self.principal_point_x - y * self.skew
        ) / self.scale_factor_x

        if self.has_radial_distortion or self.has_tangential_distortion:
            x, y = _radial_and_tangential_undistort(
                x,
                y,
                k1=self.radial_distortion[0],
                k2=self.radial_distortion[1],
                k3=self.radial_distortion[2],
                p1=self.tangential_distortion[0],
                p2=self.tangential_distortion[1],
            )

        y = y * self.scale_factor_y + self.principal_point_y
        x = x * self.scale_factor_x + self.principal_point_x + y * self.skew

        return np.stack([x, y], axis=-1)

    def pixels_to_local_viewdirs(self, pixels: np.ndarray):
        """Return the local ray viewdirs for the provided pixels."""
        y = (pixels[..., 1] - self.principal_point_y) / self.scale_factor_y
        x = (
            pixels[..., 0] - self.principal_point_x - y * self.skew
        ) / self.scale_factor_x

        if self.has_radial_distortion or self.has_tangential_distortion:
            x, y = _radial_and_tangential_undistort(
                x,
                y,
                k1=self.radial_distortion[0],
                k2=self.radial_distortion[1],
                k3=self.radial_distortion[2],
                p1=self.tangential_distortion[0],
                p2=self.tangential_distortion[1],
            )

        viewdirs = np.stack([x, y, np.ones_like(x)], axis=-1)
        return viewdirs / np.linalg.norm(viewdirs, axis=-1, keepdims=True)

    def pixels_to_viewdirs(self, pixels: np.ndarray) -> np.ndarray:
        """Return the viewdirs for the provided pixels.

        Args:
            pixels (np.ndarray): (..., 2) tensor or np.array containing 2d
                pixel positions.

        Returns:
            np.ndarray: An array containing the normalized ray directions in
                world coordinates.
        """
        if pixels.shape[-1] != 2:
            raise ValueError("The last dimension of pixels must be 2.")

        batch_shape = pixels.shape[:-1]
        pixels = np.reshape(pixels, (-1, 2))

        local_viewdirs = self.pixels_to_local_viewdirs(pixels)
        viewdirs = matv(self.orientation.T, local_viewdirs)

        # Normalize rays.
        viewdirs /= np.linalg.norm(viewdirs, axis=-1, keepdims=True)
        viewdirs = viewdirs.reshape((*batch_shape, 3))
        return viewdirs

    # def pixels_to_rays(self, pixels: np.ndarray) -> struct.Rays:
    #     viewdirs = self.pixels_to_viewdirs(pixels)
    #     # TODO(Hang Gao @ 07/20): Use viewdirs as directions can be an issue.
    #     return struct.Rays(
    #         origins=np.broadcast_to(self.position, viewdirs.shape),
    #         directions=viewdirs,
    #     )

    def pixels_to_cosa(self, pixels: np.ndarray) -> np.ndarray:
        rays_through_pixels = self.pixels_to_viewdirs(pixels)
        return (rays_through_pixels @ self.optical_axis)[..., None]

    def pixels_to_points(
        self,
        pixels: np.ndarray,
        depth: np.ndarray,
        use_projective_depth: Optional[bool] = None,
    ) -> np.ndarray:
        """Unproject pixels by their depth.

        Args:
            pixels (np.ndarray): (..., 2) tensor or np.array containing 2d
                pixel positions.
            depth (np.ndarray): (..., 1) tensor or np.array containing the
                depth of the corresponding pixels.
            use_projective_depth (bool): Whether to use the projective depth
                model. If None, use the value of `self.use_projective_depth`.

        Returns:
            np.ndarray: An array containing the 3d points in world coordinates.
        """
        if use_projective_depth is None:
            use_projective_depth = self.use_projective_depth

        rays_through_pixels = self.pixels_to_viewdirs(pixels)
        cosa = 1 if not use_projective_depth else self.pixels_to_cosa(pixels)
        points = rays_through_pixels * depth / cosa + self.position
        return points

    def points_to_local_points(self, points: np.ndarray):
        return points_to_local_points(points, self.extrin)

    def project(
        self,
        points: np.ndarray,
        return_depth: bool = False,
        use_projective_depth: Optional[bool] = None,
    ):
        if use_projective_depth is None:
            use_projective_depth = self.use_projective_depth

        return project(
            points,
            self.intrin,
            self.extrin,
            self.radial_distortion,
            self.tangential_distortion,
            return_depth=return_depth,
            use_projective_depth=use_projective_depth,
        )

    def get_pixels(self, use_center: Optional[bool] = None):
        """Return the pixel at center or corner."""
        if use_center is None:
            use_center = self.use_center
        xx, yy = np.meshgrid(
            np.arange(self.image_size_x, dtype=np.float32),
            np.arange(self.image_size_y, dtype=np.float32),
        )
        offset = 0.5 if use_center else 0
        return np.stack([xx, yy], axis=-1) + offset

    def rescale(self, scale: float) -> "Camera":
        """Rescale the camera."""
        if scale <= 0:
            raise ValueError("scale needs to be positive.")

        camera = self.copy()
        camera.position *= scale
        return camera

    def translate(self, transl: np.ndarray) -> "Camera":
        """Translate the camera."""
        camera = self.copy()
        camera.position += transl
        return camera

    def lookat(
        self,
        position: np.ndarray,
        lookat: np.ndarray,
        up: np.ndarray,
        eps: float = 1e-6,
    ) -> "Camera":
        """Rotate the camera to look at a point.

        Copies the provided vision_sfm camera and returns a new camera that is
        positioned at `camera_position` while looking at `look_at_position`.
        Camera intrinsics are copied by this method. A common value for the
        up_vector is (0, 1, 0).

        Args:
            position (np.ndarray): A (3,) numpy array representing the position
                of the camera.
            lookat (np.ndarray): A (3,) numpy array representing the location
                the camera looks at.
            up (np.ndarray): A (3,) numpy array representing the up direction,
                whose projection is parallel to the y-axis of the image plane.
            eps (float): a small number to prevent divides by zero.

        Returns:
            Camera: A new camera that is copied from the original but is
                positioned and looks at the provided coordinates.

        Raises:
            ValueError: If the camera position and look at position are very
                close to each other or if the up-vector is parallel to the
                requested optical axis.
        """

        look_at_camera = self.copy()
        optical_axis = lookat - position
        norm = np.linalg.norm(optical_axis)
        if norm < eps:
            raise ValueError(
                "The camera center and look at position are too close."
            )
        optical_axis /= norm

        right_vector = np.cross(optical_axis, up)
        norm = np.linalg.norm(right_vector)
        if norm < eps:
            raise ValueError("The up-vector is parallel to the optical axis.")
        right_vector /= norm

        # The three directions here are orthogonal to each other and form a
        # right handed coordinate system.
        camera_rotation = np.identity(3)
        camera_rotation[0, :] = right_vector
        camera_rotation[1, :] = np.cross(optical_axis, right_vector)
        camera_rotation[2, :] = optical_axis

        look_at_camera.position = position
        look_at_camera.orientation = camera_rotation
        return look_at_camera

    def undistort_image_domain(self) -> "Camera":
        """Undistort the image domain of the camera.

        Note that this function only disable the distortion parameters. The
        acutal image undistortion should be taken care of explicitly outside.
        """
        camera = self.copy()
        camera.skew = 0
        camera.radial_distortion = np.zeros(3, dtype=np.float32)
        camera.tangential_distortion = np.zeros(2, dtype=np.float32)
        return camera

    def rescale_image_domain(self, scale: float) -> "Camera":
        """Rescale the image domain of the camera."""
        if scale <= 0:
            raise ValueError("scale needs to be positive.")

        camera = self.copy()
        camera.focal_length *= scale
        camera.principal_point *= scale
        camera.image_size = np.array(
            (
                int(round(self.image_size[0] * scale)),
                int(round(self.image_size[1] * scale)),
            )
        )
        return camera

    def crop_image_domain(
        self, left: int = 0, right: int = 0, top: int = 0, bottom: int = 0
    ) -> "Camera":
        """Crop the image domain of the camera.

        The crop parameters may not cause the camera image domain dimensions to
        become non-positive.

        Args:
            left (int): number of pixels by which to reduce (or augment, if
                negative) the image domain at the associated boundary.
            right (int): likewise.
            top (int): likewise.
            bottom (int): likewise.

        Returns:
            Camera: A camera with adjusted image dimensions. The focal length
                is unchanged, and the principal point is updated to preserve
                the original principal axis.
        """

        crop_left_top = np.array([left, top])
        crop_right_bottom = np.array([right, bottom])
        new_resolution = self.image_size - crop_left_top - crop_right_bottom
        new_principal_point = self.principal_point - crop_left_top
        if np.any(new_resolution <= 0):
            raise ValueError(
                "Crop would result in non-positive image dimensions."
            )

        new_camera = self.copy()
        new_camera.image_size = np.array(
            [int(new_resolution[0]), int(new_resolution[1])]
        )
        new_camera.principal_point = np.array(
            [new_principal_point[0], new_principal_point[1]]
        )
        return new_camera

    def copy(self) -> "Camera":
        return copy.deepcopy(self)


class iPhoneParser():
    """Parser for the iPhone dataset."""

    def __init__(
        self,
        dataset: str,
        sequence: str,
        *,
        data_root: Optional[str] = None,
    ):
        self.dataset = dataset
        self.sequence = sequence
        self.data_root = data_root or os.path.abspath(
            os.path.join(os.path.dirname(__file__), "..", "..", "datasets")
        )
        self.data_dir = os.path.join(self.data_root, self.dataset, self.sequence)

        self.use_undistort = False

        (
            self._center,
            self._scale,
            self._near,
            self._far,
        ) = self._load_scene_info(self.data_dir)
        (
            self._frame_names_map,
            self._time_ids,
            self._camera_ids,
        ) = self._load_metadata_info(self.data_dir)
        self._load_extra_info()

        self.splits_dir = os.path.join(self.data_dir, "splits")

    def load_rgba(self, time_id: int, camera_id: int) -> np.ndarray:
        frame_name = self._frame_names_map[time_id, camera_id]
        rgb_path = os.path.join(self.data_dir, "rgb", f"{self._factor}x", frame_name + ".png")
        if os.path.exists(rgb_path):
            rgba = load_img(rgb_path, flags=cv2.IMREAD_UNCHANGED)
            if rgba.shape[-1] == 3:
                rgba = np.concatenate(
                    [rgba, np.full_like(rgba[..., :1], 255)], axis=-1
                )
        else:
            raise ValueError(f"RGB image not found: {rgb_path}.")
        return rgba

    def load_depth(
        self,
        time_id: int,
        camera_id: int,
    ) -> np.ndarray:
        frame_name = self._frame_names_map[time_id, camera_id]
        depth_path = os.path.join(
            self.data_dir, "depth", f"{self._factor}x", frame_name + ".npy"
        )
        depth = np.load(depth_path) * self.scale
        camera = self.load_camera(time_id, camera_id)
        # The original depth data is projective; convert it to ray traveling
        # distance.
        depth = depth / camera.pixels_to_cosa(camera.get_pixels())
        return depth

    def load_camera(self, time_id: int, camera_id: int) -> Camera:
        frame_name = self._frame_names_map[time_id, camera_id]
        camera = (
            Camera.fromjson(
                os.path.join(self.data_dir, "camera", frame_name + ".json")
            )
            .rescale_image_domain(1 / self._factor)
            .translate(-self._center)
            .rescale(self._scale)
        )
        return camera

    def load_covisible(
        self, time_id: int, camera_id: int, split: str, **_
    ) -> np.ndarray:
        frame_name = self._frame_names_map[time_id, camera_id]
        covisible_path = os.path.join(self.data_dir, "covisible", f"{self._factor}x", split, frame_name + ".png")
        if os.path.exists(covisible_path):
            # (H, W, 1) uint8 mask.
            covisible = load_img(covisible_path)[..., :1]
        else:
            raise ValueError(
                f"Covisible image not found: {covisible_path}. If not "
                f"processed before, please consider running "
                f"tools/process_covisible.py."
            )
        return covisible

    def _load_extra_info(self) -> None:
        extra_path = os.path.join(self.data_dir, "extra.json")
        extra_dict = load_json(extra_path)
        self._factor = extra_dict["factor"]
        self._fps = extra_dict["fps"]
        self._bbox = np.array(extra_dict["bbox"], dtype=np.float32)
        self._lookat = np.array(extra_dict["lookat"], dtype=np.float32)
        self._up = np.array(extra_dict["up"], dtype=np.float32)

    @staticmethod
    def _load_scene_info(data_dir: str) -> tuple[np.ndarray, float, float, float]:
        scene_dict = load_json(os.path.join(data_dir, "scene.json"))
        center = np.array(scene_dict["center"], dtype=np.float32)
        scale = scene_dict["scale"]
        near = scene_dict["near"]
        far = scene_dict["far"]
        return center, scale, near, far

    @staticmethod
    def _load_metadata_info(data_dir: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        dataset_dict = load_json(os.path.join(data_dir, "dataset.json"))
        _frame_names = np.array(dataset_dict["ids"])

        metadata_dict = load_json(os.path.join(data_dir, "metadata.json"))
        time_ids = np.array(
            [metadata_dict[k]["warp_id"] for k in _frame_names], dtype=np.uint32
        )
        camera_ids = np.array(
            [metadata_dict[k]["camera_id"] for k in _frame_names], dtype=np.uint32
        )

        frame_names_map = np.zeros(
            (time_ids.max() + 1, camera_ids.max() + 1), _frame_names.dtype
        )
        for i, (t, c) in enumerate(zip(time_ids, camera_ids)):
            frame_names_map[t, c] = _frame_names[i]

        return frame_names_map, time_ids, camera_ids

    @property
    def frame_names(self):
        return self._frame_names_map[self.time_ids, self.camera_ids]

    @property
    def time_ids(self):
        return self._time_ids

    @property
    def camera_ids(self):
        return self._camera_ids

    @property
    def center(self):
        return self._center

    @property
    def scale(self):
        return self._scale

    @property
    def near(self):
        return self._near

    @property
    def far(self):
        return self._far

    @property
    def factor(self):
        return self._factor

    @property
    def fps(self):
        return self._fps

    @property
    def bbox(self):
        return self._bbox

    @property
    def lookat(self):
        return self._lookat

    @property
    def up(self):
        return self._up


def cam_c2w_interp(T1: np.ndarray, T2: np.ndarray, t: float):  # T1 and T2 are camera-to-world matrices
    assert 0 <= t <= 1

    # to quaternion
    q1 = Rotation.from_matrix(T1[:3, :3])
    q2 = Rotation.from_matrix(T2[:3, :3])

    # translation vectors
    p1 = T1[:3, 3]
    p2 = T2[:3, 3]

    # rotation SLERP
    key_rots = Rotation.from_matrix([T1[:3, :3], T2[:3, :3]])
    slerp = Slerp([0, 1], key_rots)
    R_interp = slerp(t).as_matrix()

    # translation LERP
    p_interp = (1 - t) * p1 + t * p2

    # recompose
    T_interp = np.identity(4)
    T_interp[:3, :3] = R_interp
    T_interp[:3, 3] = p_interp
    return T_interp


def cam_K_interp(K1: np.ndarray, K2: np.ndarray, t: float):
    assert 0 <= t <= 1
    K_interp = (1 - t) * K1 + t * K2
    return K_interp


def get_c2w_mat(cam_dict: dict) -> np.ndarray:
    T = np.eye(4)
    T[:3, :3] = np.array(cam_dict["orientation"]).reshape(3, 3).T  # "orientation" is w2c
    T[:3, 3] = np.array(cam_dict["position"]).reshape(3)

    K = np.eye(3)
    K[0, 0] = cam_dict["focal_length"]
    K[1, 1] = cam_dict["focal_length"]
    K[0, 2] = cam_dict["principal_point"][0]
    K[1, 2] = cam_dict["principal_point"][1]

    return T, K


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--data_root",
        type=str,
        default="/disk1/ryotaro/data/iphone",
    )
    parser.add_argument(
        "--sequence",
        choices=['apple', 'block', 'teddy', 'paper-windmill', 'spin'],
    )
    parser.add_argument(
        "--output_folder",
        type=str,
        default="./dycheck_rendered"
    )
    parser.add_argument(
        "--use_mesh",
        action="store_true",
        help="Use mesh-based rendering.",
    )
    parser.add_argument(
        "--save_trajectory_type",
        type=str,
        default=None,
        choices=[None, "2d_npy"],
        help="If specified, save additional trajectories.",
    )
    parser.add_argument(
        "--gpu_id",
        type=int,
        default=0,
    )

    args = parser.parse_args()
    assert args.data_root.endswith("iphone")


    @torch.no_grad()
    def run_trajectory(src_cam: int, tgt_cam: int, time_id: int, use_mesh: bool, save_trajectory_type: Optional[str] = None):

        src_frame_name = parser._frame_names_map[time_id, src_cam]
        tgt_frame_name = parser._frame_names_map[time_id, tgt_cam]
        image_names = [
            os.path.join(parser.data_dir, "rgb", f"{parser._factor}x", src_frame_name + ".png"),
            os.path.join(parser.data_dir, "rgb", f"{parser._factor}x", tgt_frame_name + ".png"),
        ]
        if not all([os.path.isfile(p) for p in image_names]):
            return None

        images = load_and_preprocess_images(image_names).to(f"cuda:{args.gpu_id}")
        with torch.amp.autocast("cuda", dtype=torch.bfloat16 if torch.cuda.get_device_capability()[0] >= 8 else torch.float16):
            images = images[None]  # add batch dimension
            aggregated_tokens_list, ps_idx = model.aggregator(images)
            # Predict Cameras
            pose_enc = model.camera_head(aggregated_tokens_list)[-1]
            # Extrinsic and intrinsic matrices, following OpenCV convention (camera from world)
            extrinsic, intrinsic = pose_encoding_to_extri_intri(pose_enc, images.shape[-2:])

            # Predict Depth Maps
            depth_map, depth_conf = model.depth_head(aggregated_tokens_list, images, ps_idx)

        # postprocess
        rgb = rearrange(images, "() v c h w -> v h w c", v=2, c=3).cpu().numpy()
        rgb = np.clip(255 * rgb, 0, 255).astype(np.uint8)
        _, height, width, _ = rgb.shape

        depth_map = rearrange(depth_map, "() v h w () -> v h w", v=2).cpu().numpy()

        extrinsic_3x4 = extrinsic.squeeze(0).cpu().numpy()
        intrinsic = intrinsic.squeeze(0).cpu().numpy()

        extrinsic = np.eye(4)[None, :, :].repeat(extrinsic_3x4.shape[0], axis=0)
        extrinsic[:, :3, :4] = extrinsic_3x4

        # interpolate
        poses = np.linalg.inv(extrinsic)
        poses_interp = [cam_c2w_interp(poses[0], poses[1], t) for t in np.linspace(0, 1, num=25)]
        intrinsic_interp = [cam_K_interp(intrinsic[0], intrinsic[1], t) for t in np.linspace(0, 1, num=25)]

        save_path = os.path.join(args.output_folder, f"{parser.sequence}_{src_cam}_{tgt_cam}_{time_id:05d}", "warped")
        os.makedirs(save_path, exist_ok=True)

        never_occluded = np.ones_like(depth_map[0], dtype=bool)

        # rendering
        trans_coordinates_3D_list = []
        trans_valid_list = []

        for i, (pose, intr) in enumerate(zip(poses_interp, intrinsic_interp)):
            extr = np.linalg.inv(pose)
            np.save(os.path.join(save_path, str(i).zfill(4)+"_pose.npy"), extr)

            if use_mesh:

                warped_frame2, mask2, trans_coordinates_3D, trans_valid = render_mesh(
                    rgb[0],
                    depth_map[0],
                    extrinsic[0],
                    extr,
                    intrinsic[0],
                    intr,
                    mask_deocclusion=True, # no_occlusion_revealing,
                    mask_postprocess_opening_kernel_size=1
                )

                if i == 0:
                    warped_frame2 = rgb[0]
                    mask2 = np.zeros_like(mask2)

                # binarize masks
                mask2 = np.where(mask2 > 0, 255, 0).astype(np.uint8)

                # save images
                warped_frame2[mask2 > 0] = 0
                Image.fromarray(mask2).save(os.path.join(save_path, str(i).zfill(4)+"_mask.png"))
                Image.fromarray(warped_frame2).save(os.path.join(save_path, str(i).zfill(4)+".png"))

            else:
                warped_frame2, mask2, trans_coordinates_3D, trans_valid = forward_warp(
                    rgb[0],
                    never_occluded,
                    depth_map[0],
                    extrinsic[0],
                    extr,
                    intrinsic[0],
                    intr,
                )
                never_occluded *= trans_valid

                # save images
                mask = 1 - mask2
                mask[mask < 0.5] = 0
                mask[mask >= 0.5] = 1
                mask = np.repeat(mask[:,:,np.newaxis]*255., repeats=3, axis=2)

                kernel = np.ones((5,5), np.uint8)
                mask_erosion = cv2.dilate(np.array(mask), kernel)
                mask_erosion = Image.fromarray(np.uint8(mask_erosion))
                mask_erosion.save(os.path.join(save_path, str(i).zfill(4)+"_mask.png"))

                mask_erosion_ = np.array(mask_erosion)/255.
                mask_erosion_[mask_erosion_ < 0.5] = 0
                mask_erosion_[mask_erosion_ >= 0.5] = 1
                warped_frame2 = Image.fromarray(np.uint8(warped_frame2 * (1-mask_erosion_)))
                warped_frame2.save(os.path.join(save_path, str(i).zfill(4)+".png"))

            trans_coordinates_3D_list.append(trans_coordinates_3D)
            trans_valid_list.append(trans_valid)

        Image.fromarray(rgb[1]).save(os.path.join(save_path, str(i).zfill(4) + "_target.png"))

        if save_trajectory_type == "2d_npy":
            trans_coordinates_list = [coords[:, :, :2] for coords in trans_coordinates_3D_list]

            # overwrite the first frame trans coordinates and valid (just in case)
            trans_coordinates_list[0] = create_grid(height, width)
            trans_valid_list[0] = trans_valid_list[0] + True

            trans_coordinates = np.stack(trans_coordinates_list, axis=0)
            trans_valid = np.stack(trans_valid_list, axis=0)
            np.save(os.path.join(save_path, 'trans_coordinates.npy'), trans_coordinates)
            np.save(os.path.join(save_path, 'trans_valid.npy'), trans_valid)
        elif save_trajectory_type is not None:
            raise NotImplementedError(f"Save trajectory type '{save_trajectory_type}' is not implemented.")

        return save_path


    # select processable scenes
    parser = iPhoneParser(dataset="iphone", sequence=args.sequence, data_root=os.path.dirname(args.data_root))
    parser._factor = 1
    src_cam = 0
    tgt_cam = 1

    # prepare VGGT
    model = VGGT.from_pretrained("facebook/VGGT-1B").to(f"cuda:{args.gpu_id}").eval()

    os.makedirs(args.output_folder, exist_ok=True)

    for idx, time_id in enumerate(tqdm(parser.time_ids, desc=args.sequence)):
        run_trajectory(src_cam, tgt_cam, time_id, use_mesh=args.use_mesh, save_trajectory_type=args.save_trajectory_type)